server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://cdb-obab2ln3.gz.tencentcdb.com:10005/newOA?useUnicode=true&useSSL=false&characterEncoding=utf8&severTimezone=Asia/Shanghai
    #url: jdbc:mysql://127.0.0.1:3306/newoa?useUnicode=true&useSSL=false&characterEncoding=utf8&severTimezone=Asia/Shanghai
    username: root
    password: xy123456
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  configuration:
#    default-enum-type-handler: com.study.sys.utils.handler.EnumBaseHandler
#  mapper-locations: classpath:mybatis/*.xml
#  mapper-locations: classpath:mybatis/*.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#    default-enum-type-handler: com.study.sys.utils.handler.EnumBaseHandler
#  mapper-locations: mybatis/*.xml
#  type-aliases-package: com.study.sys.entity
#  typeEnumsPackage: com.study.sys.enums

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.study.sys.entity
  typeEnumsPackage: com.study.sys.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: com.study.sys.utils.handler.EnumBaseHandler
#    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

logging:
  config: classpath:logback-spring.xml


